import { createClient } from '@/lib/supabase/server'
import { redirect } from 'next/navigation'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { EUROPEAN_COUNTRIES } from '@/types'

export default async function AdminVisaPage() {
  const supabase = createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')
  const { data: profile } = await supabase.from('users').select('role').eq('id', user.id).single()
  if (profile?.role !== 'admin') redirect('/dashboard')

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-[#1E3A5F]">Visa Information</h1>
        <p className="text-muted-foreground">Coverage across {EUROPEAN_COUNTRIES.length} European countries</p>
      </div>
      <Card>
        <CardHeader><CardTitle>Supported Countries</CardTitle></CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-3">
            {EUROPEAN_COUNTRIES.map(country => (
              <div key={country} className="p-3 bg-gray-50 rounded-lg text-sm font-medium text-center">
                {country}
              </div>
            ))}
          </div>
          <p className="text-sm text-muted-foreground mt-4">Visa guides are generated by AI based on official requirements. Content is updated dynamically.</p>
        </CardContent>
      </Card>
    </div>
  )
}
